version: "3"

# Please copy config/config.example.yaml to config/config.yaml and fill in the variables

services:
    onlinetorrent:
        image: darknightlab/OnlineTorrent-Backend:latest
        # build: .
        container_name: onlinetorrent
        restart: always
        ports:
            - 23333:80
        volumes:
            - ./config:/OnlineTorrent-Backend/config
