port: 80
authtoken: 123456

qbservers:
  - name: qBittorrent1
    qbURL: http://127.0.0.1:8888
    webseedURL: https://127.0.0.1:80
    username: username
    password: password
    category: projectj
    ratioLimit: # undefined is no limit
    seedingTimeLimit: # minutes, undefined is no limit
    sequentialDownload: true
    firstLastPiecePrio: true
